### ISSUE TITLE
Initial Checklist for Package Setup

### ISSUE THREAD

**Issue by dyvasey** [gdmate/gdmate#2]
Here is our initial checklist (presented at 7/5/22 CIG staff meeting) for getting the repository started. This issue is to track progress on implementing this.

- [x] Create initial repository

- [x] Outline best practices for contributing code (e.g., pull requests)
_Require all pull requests to be reviewed by another maintainter_

- [x] #12
_Exists but no content yet_

- [x] #4
_GPL v2.0 but need to add file_

- [x] Set up packaging with pip and conda (including handling dependencies)
_Basic setup.py and meta.yaml implemented_

- [x] Set up test for a simple piece of python code
_Have simple unittest for helloworld script_

- [x] #9

- [x] #6

- [x] #11 

- [x] Set up Binder environment

- [ ] Integrate initial series of python code (source)

- [x] #18

- [ ] Add python style guide with testing

Secondary Item Checklist (migrate to new issue after initial checklist completed)

- [x] #17
- [ ] Enable use and testing of Julia in the repository
- [ ] Determine options for python code optimization (Numba, Cython, dash, etc) in the context of use with Julia
- [x] Add a tutorial/notes for creating a python repository/package
- [ ] Go through CIG example repository
- [ ] Decide on way people should be assigned credit for their work in addition to standard contributor/developer list (ex: author name on top of function)?
